version: "2"
services:
  dev:
    build: dev/
    links:
      - prod
    volumes:
      - /share:/var/share/
  prod:
    build: prod/
    ports:
      - "8080:8080"
    volumes:
      - /share:/usr/local/tomcat9/webapps



