version: '2'
services:
   dev:
    build: dev/
    volumes:
      - share1:/var/share/
   prod:
    build: prod/
    ports:
      - "8080:8080"
    volumes:
      - share1:/usr/local/tomcat9/webapps/
volumes:
  share1:
