version: '2'
services:
   dev:
    image: maven:latest
    command: >
             bash -c "git clone https://github.com/yura40klg/42paas.git /var/app 
             && cd /var/app && mvn clean && mvn install && mkdir /var/share && mkdir /var/share/cfg
             && cp /var/app/target/App42PaaS-Java-MySQL-Sample-0.0.1-SNAPSHOT.war /var/share/app.war
             && cp /var/app//WebContent/Config.properties /var/share/cfg/Config.properties"
    volumes:
      - share1:/var/share/
      - share2:/var/share/cfg/Config.properties
   prod:
    image: tomcat: latest
    ports:
      - "8080:8080"
    volumes:
      - share1:/usr/local/tomcat/webapps/
      - share2:/usr/local/tomcat/ROOT
   db:
    image: mysql:5.7
    container_name: db
    restart: always
    environment:
          - MYSQL_ROOT_PASSWORD=qwerty
          - MYSQL_DATABASE=my_db
          - MYSQL_USER=db_user
          - MYSQL_PASSWORD=qwerty

volumes:
  share1:
  share2:
