version: "3.7"
services:
  dev:
    build: dev/
    volumes:
      - ./share:/var/share
  prod:
    build: prod/
    volumes:
      - ./share:/usr/local/tomcat9/webapps
    ports:
      - "8080:8080"

